name: Request Cloud Storage Bucket
description: Self-service bucket request (AWS S3 or GCP GCS)
title: "[Bucket Request]: "
labels: ["infra-request"]
body:
  - type: dropdown
    id: cloud_provider
    attributes:
      label: Cloud Provider
      options:
        - GCP
        - AWS
    validations:
      required: true

  - type: input
    id: bucket_name
    attributes:
      label: Bucket Name
      description: Must be globally unique
      placeholder: my-app-logs-123
    validations:
      required: true

  - type: input
    id: region
    attributes:
      label: Region
      description: "GCP: asia-south1, us-central1, europe-west1 | AWS: ap-south-1, us-east-1, eu-west-1"
      placeholder: asia-south1
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - dev
        - test
        - prod
    validations:
      required: true

  - type: dropdown
    id: public_access
    attributes:
      label: Public Access
      options:
        - "false"