name: Bucket Self Service Bot

on:
  issues:
    types: [opened]

jobs:
  bucket:
    if: contains(github.event.issue.labels.*.name, 'infra-request')
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: automation   # base branch

      - name: Extract issue form values
        id: vars
        shell: bash
        run: |
          BODY="$(cat <<'EOF'
          ${{ github.event.issue.body }}
          EOF
          )"

          echo "===== ISSUE BODY ====="
          echo "$BODY"
          echo "======================"

          bucket_name=$(echo "$BODY" | awk '
            /^### Bucket Name/ {found=1; next}
            found && NF {print; exit}
          ')

          region=$(echo "$BODY" | awk '
            /^### Region/ {found=1; next}
            found && NF {print; exit}
          ')

          environment=$(echo "$BODY" | awk '
            /^### Environment/ {found=1; next}
            found && NF {print; exit}
          ')

          public_access=$(echo "$BODY" | awk '
            /^### Public Access/ {found=1; next}
            found && NF {print; exit}
          ')

          echo "bucket_name=$bucket_name" >> "$GITHUB_OUTPUT"
          echo "region=$region" >> "$GITHUB_OUTPUT"
          echo "environment=$environment" >> "$GITHUB_OUTPUT"
          echo "public_access=$public_access" >> "$GITHUB_OUTPUT"

      - name: Print issue outputs
        run: |
          echo "bucket_name='${{ steps.vars.outputs.bucket_name }}'"
          echo "region='${{ steps.vars.outputs.region }}'"
          echo "environment='${{ steps.vars.outputs.environment }}'"
          echo "public_access='${{ steps.vars.outputs.public_access }}'"


      - name: Generate Terraform File
        run: |
          BUCKET="${{ steps.vars.outputs.bucket_name }}"
          REGION="${{ steps.vars.outputs.region }}"
          ENV="${{ steps.vars.outputs.environment }}"

          cat <<EOF >> Projects/gcs.tf

          resource "google_storage_bucket" "${{ steps.vars.outputs.bucket_name }}" {
            name     = "${{ steps.vars.outputs.bucket_name }}"
            location = "${{ steps.vars.outputs.region }}"

            uniform_bucket_level_access = true
            public_access_prevention    = "enforced"

            labels = {
              env   = "${{ steps.vars.outputs.environment }}"
              owner = "selfservice"
            }
          }
          EOF

      - name: Format Terraform
        uses: hashicorp/setup-terraform@v2

      - run: terraform fmt Projects/gcs.tf
      - name: Debug Token
        run: |
          if [ -z "${{ secrets.INFRA_BOT_PAT }}" ]; then
            echo "PAT is empty"
            exit 1
          else
            echo "PAT exists"
          fi
      - name: Debug GH auth
        env:
          GH_TOKEN: ${{ secrets.INFRA_BOT_PAT }}
        run: |
          gh auth status || true
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.INFRA_BOT_PAT }}
        run: |
          BRANCH_NAME="bucket-${{ steps.vars.outputs.bucket_name }}-${{ github.run_id }}"

          git config --global user.name "infra-selfservice-bot"
          git config --global user.email "infra-bot@users.noreply.github.com"

          git checkout -b "$BRANCH_NAME"
          git add Projects/gcs.tf
          git commit -m "Auto: bucket ${{ steps.vars.outputs.bucket_name }}-${{ github.run_id }}"
          git push origin "$BRANCH_NAME"


          gh pr create \
            --base automation \
            --head "$BRANCH_NAME" \
            --title "Self-service bucket: ${{ steps.vars.outputs.bucket_name }}-${{ github.run_id }}" \
            --body "Bucket: ${{ steps.vars.outputs.bucket_name }} | Region: ${{ steps.vars.outputs.region }} | Env: ${{ steps.vars.outputs.environment }}"

          gh pr edit "$BRANCH_NAME" --add-label "ready-for-plan"
