name: Terraform dry run

on:
  pull_request:
    branches:
      - automation   # PR to automation triggers this

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    defaults:
      run:
        working-directory: Projects   # change if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3

      # Authenticate to GCP using Service Account JSON
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Infracost #For cost estimation
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan
      
      - name: Convert plan to human-readable json format
        run: terraform show -json tfplan > tfplan.json
      
      - name: Terraform Plan Summary
        run: |
          echo "## Terraform Plan Summary" > summary.md
          echo "" >> summary.md
          terraform show -no-color tfplan >> summary.md

      - name: Infracost Breakdown
        working-directory: Projects
        run: |
          infracost breakdown --path Projects --format json --out-file Projects/infracost.json

      - name: Infracost Comment
        uses: infracost/actions/comment@v1.1.2
        with:
          path: Projects/infracost.json
          behavior: update

      - name: Comment Plan on PR
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const summary = fs.readFileSync('Projects/summary.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary.substring(0, 65000)
            });
