name: Terraform Plan CI

on:
  pull_request:
    branches:
      - automation   # PR to automation triggers this

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Projects   # change if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3

      # Auth will be added later (OIDC or SA key)
      # For now we skip backend auth issues

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color