name: Terraform Security Scan # Checkov

on:
  pull_request:
    branches: [automation]

jobs:
  checkov:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Projects

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov #Soft Governance Mode - Report only, do not fail PR
        run: |
          checkov -d . \
            --quiet \
            --soft-fail

      - name: Enfore Checkov #Enforce Critical - Fail PR on HIGH severity
        run: |
         checkov -d . \
            --severity-level HIGH